# Basic
name:               "Pulse trains to percepts"

# URL
baseurl:            "http://uwescience.github.io/pulse2percept/"

# Markdown
markdown:           rdiscount

# Navigation
nav:
  - name:           "Vision and Cognition lab"
    href:           "//courses.washington.edu/viscog/index.html"
  - name:           "eScience Institute"
    href:           "//escience.washington.edu"
  - name:           "Code"
    href:           "//github.com/uwescience/pulse2percept"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
